export {
  HomePageTagline,
  HomePageHeadline,
  ValueProposition,
  DirectFromProducerMessage,
  ProductTrustBanner,
  ProducerPriceExplanation,
  OrderSummaryImpact,
  OrderConfirmationMessage,
  CartImpactSummary,
  VerifiedProducerBadge,
  ShopLocalCTA,
  BecomeProducerCTA,
  MissionStatement,
  ImpactStats,
} from "./ConversionCopy"
