import { Migration } from "@medusajs/framework/mikro-orm/migrations";

export class Migration20260706210818 extends Migration {

  override async up(): Promise<void> {
    this.addSql(`create table if not exists "garden_time_credit" ("id" text not null, "garden_id" text not null, "customer_id" text not null, "membership_id" text not null, "amount" numeric not null, "hours_equivalent" numeric not null, "source_type" text check ("source_type" in ('volunteer_log', 'work_party', 'gift', 'bonus', 'adjustment')) not null, "source_id" text null, "hourly_rate" numeric not null, "status" text check ("status" in ('pending', 'available', 'redeemed', 'expired', 'cancelled')) not null default 'pending', "redeemed_at" timestamptz null, "redeemed_for_type" text null, "redeemed_for_id" text null, "expires_at" timestamptz null, "credit_ledger_entry_id" text null, "redemption_ledger_entry_id" text null, "notes" text null, "metadata" jsonb null, "raw_amount" jsonb not null, "raw_hours_equivalent" jsonb not null, "raw_hourly_rate" jsonb not null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "garden_time_credit_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_garden_time_credit_deleted_at" ON "garden_time_credit" ("deleted_at") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "garden_work_party" ("id" text not null, "garden_id" text not null, "season_id" text null, "name" text not null, "description" text null, "date" timestamptz not null, "start_time" timestamptz not null, "end_time" timestamptz not null, "duration_hours" numeric not null, "max_volunteers" integer null, "min_volunteers" integer null, "current_signups" integer not null default 0, "actual_attendance" integer null, "activity_types" jsonb not null, "tasks" jsonb null, "status" text check ("status" in ('draft', 'scheduled', 'open', 'full', 'in_progress', 'complete', 'cancelled')) not null default 'draft', "organizer_id" text not null, "co_organizer_ids" jsonb null, "credit_multiplier" numeric not null default 1, "bonus_reason" text null, "requirements" text null, "skill_level" text check ("skill_level" in ('beginner', 'intermediate', 'advanced', 'all')) not null default 'all', "meeting_point" text null, "parking_info" text null, "rain_date" timestamptz null, "weather_cancellation_policy" text null, "refreshments_provided" boolean not null default false, "refreshments_notes" text null, "total_volunteer_hours" numeric null, "accomplishments" text null, "photo_urls" jsonb null, "notes" text null, "metadata" jsonb null, "raw_duration_hours" jsonb not null, "raw_credit_multiplier" jsonb not null default '{"value":"1","precision":20}', "raw_total_volunteer_hours" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "garden_work_party_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_garden_work_party_deleted_at" ON "garden_work_party" ("deleted_at") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "garden_work_party_signup" ("id" text not null, "work_party_id" text not null, "garden_id" text not null, "customer_id" text not null, "membership_id" text not null, "status" text check ("status" in ('signed_up', 'confirmed', 'attended', 'no_show', 'cancelled')) not null default 'signed_up', "checked_in_at" timestamptz null, "checked_out_at" timestamptz null, "actual_hours" numeric null, "tasks_completed" jsonb null, "is_lead" boolean not null default false, "lead_area" text null, "organizer_notes" text null, "volunteer_notes" text null, "signed_up_at" timestamptz not null, "confirmed_at" timestamptz null, "cancelled_at" timestamptz null, "cancellation_reason" text null, "metadata" jsonb null, "raw_actual_hours" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "garden_work_party_signup_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_garden_work_party_signup_deleted_at" ON "garden_work_party_signup" ("deleted_at") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "volunteer_log" ("id" text not null, "garden_id" text not null, "customer_id" text not null, "membership_id" text not null, "activity_type" text check ("activity_type" in ('planting', 'weeding', 'watering', 'harvesting', 'maintenance', 'composting', 'mulching', 'pest_control', 'tool_maintenance', 'teaching', 'coordination', 'administration', 'outreach', 'fundraising', 'other')) not null, "description" text null, "date" timestamptz not null, "start_time" timestamptz null, "end_time" timestamptz null, "hours" numeric not null, "plot_id" text null, "area" text null, "verified_by_id" text null, "verification_status" text check ("verification_status" in ('pending', 'verified', 'disputed', 'rejected')) not null default 'pending', "verified_at" timestamptz null, "verification_notes" text null, "self_verified" boolean not null default false, "ledger_entry_id" text null, "credits_earned" numeric null, "credit_rate" numeric null, "work_party_id" text null, "bonus_multiplier" numeric not null default 1, "bonus_reason" text null, "photo_urls" jsonb null, "notes" text null, "metadata" jsonb null, "raw_hours" jsonb not null, "raw_credits_earned" jsonb null, "raw_credit_rate" jsonb null, "raw_bonus_multiplier" jsonb not null default '{"value":"1","precision":20}', "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "volunteer_log_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_volunteer_log_deleted_at" ON "volunteer_log" ("deleted_at") WHERE deleted_at IS NULL;`);
  }

  override async down(): Promise<void> {
    this.addSql(`drop table if exists "garden_time_credit" cascade;`);

    this.addSql(`drop table if exists "garden_work_party" cascade;`);

    this.addSql(`drop table if exists "garden_work_party_signup" cascade;`);

    this.addSql(`drop table if exists "volunteer_log" cascade;`);
  }

}
