import { model } from "@medusajs/framework/utils"

/**
 * Share Box
 *
 * A per-cycle materialization of a share-box subscription. Generated by
 * `OrderCycleModuleService#generateBoxesForCycle` from the subscription's
 * template, the cycle's available products, and any subscriber-specific
 * slot overrides.
 *
 * Lifecycle:
 *   pending      — generated but not yet picked
 *   allocated    — variants chosen and reserved against the cycle product
 *   packed       — physically packed, ready for handoff
 *   dispatched   — handed off via the cycle's outgoing exchange
 *   skipped      — generation skipped this cycle (e.g. paused subscription
 *                  caught after generation, or a slot could not be filled)
 *   cancelled    — cancelled after generation
 *
 * The realized contents are stored as JSON on `items` for the same
 * reason ShareBoxTemplate's slots are JSON: keep the surface
 * approachable, enforce shape via service validation.
 *
 * Item shape:
 *   {
 *     "slot_key": "leafy_green",
 *     "variant_id": "var_123",
 *     "quantity": 1,
 *     "unit_price": 450,        // cycle-time price snapshot, minor units
 *     "currency_code": "usd"
 *   }
 */
const ShareBox = model.define("share_box", {
  id: model.id().primaryKey(),

  share_box_subscription_id: model.text(),
  share_box_template_id: model.text(),
  order_cycle_id: model.text(),

  customer_id: model.text().nullable(),
  customer_external_id: model.text().nullable(),

  status: model
    .enum([
      "pending",
      "allocated",
      "packed",
      "dispatched",
      "skipped",
      "cancelled",
    ])
    .default("pending"),

  items: model.json(),

  // Sum of items[].unit_price * items[].quantity at allocation time.
  // null until the scheduler has resolved every slot.
  total_price: model.bigNumber().nullable(),
  currency_code: model.text().default("usd"),

  // If a slot could not be filled, the affected slot key(s) are recorded
  // here and the box transitions to `skipped` rather than being silently
  // shorted.
  unfilled_slot_keys: model.json().nullable(),

  generated_at: model.dateTime(),
  allocated_at: model.dateTime().nullable(),
  dispatched_at: model.dateTime().nullable(),

  metadata: model.json().nullable(),
})
  .indexes([
    {
      name: "IDX_SB_SUBSCRIPTION",
      on: ["share_box_subscription_id"],
    },
    {
      name: "IDX_SB_CYCLE",
      on: ["order_cycle_id"],
    },
    {
      name: "IDX_SB_CYCLE_STATUS",
      on: ["order_cycle_id", "status"],
    },
    {
      name: "IDX_SB_CUSTOMER",
      on: ["customer_id"],
    },
    {
      name: "IDX_SB_EXTERNAL",
      on: ["customer_external_id"],
    },
    {
      name: "UQ_SB_SUBSCRIPTION_CYCLE",
      on: ["share_box_subscription_id", "order_cycle_id"],
      unique: true,
    },
  ])

export default ShareBox
