import { Migration } from "@medusajs/framework/mikro-orm/migrations";

export class Migration20260706210819 extends Migration {

  override async up(): Promise<void> {
    this.addSql(`create table if not exists "garden_proposal" ("id" text not null, "garden_id" text not null, "title" text not null, "description" text not null, "summary" text null, "proposal_type" text check ("proposal_type" in ('budget', 'policy', 'membership', 'infrastructure', 'governance', 'allocation', 'season_plan', 'partnership', 'other')) not null, "proposed_by_id" text not null, "co_sponsors" jsonb null, "voting_start" timestamptz not null, "voting_end" timestamptz not null, "quorum_required" numeric not null, "approval_threshold" numeric not null, "status" text check ("status" in ('draft', 'submitted', 'active', 'passed', 'rejected', 'tie', 'implemented', 'withdrawn', 'expired')) not null default 'draft', "votes_for" numeric not null default 0, "votes_against" numeric not null default 0, "votes_abstain" numeric not null default 0, "total_voting_power" numeric not null default 0, "unique_voters" integer not null default 0, "eligible_voters" integer null, "eligible_voting_power" numeric null, "result_calculated_at" timestamptz null, "quorum_met" boolean null, "approval_percentage" numeric null, "implementation_notes" text null, "implemented_at" timestamptz null, "implemented_by_id" text null, "budget_request" jsonb null, "policy_changes" jsonb null, "attachment_urls" jsonb null, "discussion_enabled" boolean not null default true, "ledger_entry_id" text null, "notes" text null, "metadata" jsonb null, "raw_quorum_required" jsonb not null, "raw_approval_threshold" jsonb not null, "raw_votes_for" jsonb not null default '{"value":"0","precision":20}', "raw_votes_against" jsonb not null default '{"value":"0","precision":20}', "raw_votes_abstain" jsonb not null default '{"value":"0","precision":20}', "raw_total_voting_power" jsonb not null default '{"value":"0","precision":20}', "raw_eligible_voting_power" jsonb null, "raw_approval_percentage" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "garden_proposal_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_garden_proposal_deleted_at" ON "garden_proposal" ("deleted_at") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "garden_proposal_comment" ("id" text not null, "proposal_id" text not null, "garden_id" text not null, "customer_id" text not null, "content" text not null, "parent_id" text null, "visibility" text check ("visibility" in ('public', 'members_only')) not null default 'members_only', "status" text check ("status" in ('visible', 'hidden', 'flagged', 'removed')) not null default 'visible', "moderated_by_id" text null, "moderation_reason" text null, "likes_count" integer not null default 0, "is_edited" boolean not null default false, "edited_at" timestamptz null, "posted_at" timestamptz not null, "metadata" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "garden_proposal_comment_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_garden_proposal_comment_deleted_at" ON "garden_proposal_comment" ("deleted_at") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "garden_role" ("id" text not null, "garden_id" text not null, "name" text not null, "slug" text not null, "description" text null, "role_type" text check ("role_type" in ('elected', 'appointed', 'automatic', 'volunteer')) not null, "permissions" jsonb not null, "voting_power_bonus" numeric not null default 0, "can_appoint" jsonb null, "term_months" integer null, "max_consecutive_terms" integer null, "max_holders" integer null, "min_holders" integer null, "is_active" boolean not null default true, "is_system" boolean not null default false, "metadata" jsonb null, "raw_voting_power_bonus" jsonb not null default '{"value":"0","precision":20}', "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "garden_role_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_garden_role_deleted_at" ON "garden_role" ("deleted_at") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "garden_role_assignment" ("id" text not null, "role_id" text not null, "garden_id" text not null, "customer_id" text not null, "membership_id" text not null, "assigned_at" timestamptz not null, "assigned_by_id" text null, "assignment_method" text check ("assignment_method" in ('elected', 'appointed', 'automatic', 'volunteered')) not null, "term_start" timestamptz not null, "term_end" timestamptz null, "term_number" integer not null default 1, "status" text check ("status" in ('active', 'on_leave', 'suspended', 'ended')) not null default 'active', "ended_at" timestamptz null, "end_reason" text check ("end_reason" in ('term_complete', 'resigned', 'removed', 'replaced')) null, "election_proposal_id" text null, "notes" text null, "metadata" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "garden_role_assignment_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_garden_role_assignment_deleted_at" ON "garden_role_assignment" ("deleted_at") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "garden_vote" ("id" text not null, "proposal_id" text not null, "garden_id" text not null, "customer_id" text not null, "membership_id" text not null, "vote" text check ("vote" in ('for', 'against', 'abstain')) not null, "voting_power" numeric not null, "power_basis" jsonb not null, "comment" text null, "comment_visibility" text check ("comment_visibility" in ('public', 'members_only', 'private')) not null default 'public', "delegated_from_id" text null, "is_delegated" boolean not null default false, "is_final" boolean not null default true, "previous_vote" text check ("previous_vote" in ('for', 'against', 'abstain')) null, "voted_at" timestamptz not null, "metadata" jsonb null, "raw_voting_power" jsonb not null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "garden_vote_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_garden_vote_deleted_at" ON "garden_vote" ("deleted_at") WHERE deleted_at IS NULL;`);

    this.addSql(`create table if not exists "garden_vote_delegation" ("id" text not null, "garden_id" text not null, "delegator_id" text not null, "delegator_membership_id" text not null, "delegate_id" text not null, "delegate_membership_id" text not null, "scope" text check ("scope" in ('all', 'category', 'single')) not null default 'all', "proposal_types" jsonb null, "proposal_id" text null, "effective_from" timestamptz not null, "effective_until" timestamptz null, "status" text check ("status" in ('active', 'revoked', 'expired')) not null default 'active', "revoked_at" timestamptz null, "reason" text null, "metadata" jsonb null, "created_at" timestamptz not null default now(), "updated_at" timestamptz not null default now(), "deleted_at" timestamptz null, constraint "garden_vote_delegation_pkey" primary key ("id"));`);
    this.addSql(`CREATE INDEX IF NOT EXISTS "IDX_garden_vote_delegation_deleted_at" ON "garden_vote_delegation" ("deleted_at") WHERE deleted_at IS NULL;`);
  }

  override async down(): Promise<void> {
    this.addSql(`drop table if exists "garden_proposal" cascade;`);

    this.addSql(`drop table if exists "garden_proposal_comment" cascade;`);

    this.addSql(`drop table if exists "garden_role" cascade;`);

    this.addSql(`drop table if exists "garden_role_assignment" cascade;`);

    this.addSql(`drop table if exists "garden_vote" cascade;`);

    this.addSql(`drop table if exists "garden_vote_delegation" cascade;`);
  }

}
